#!/bin/sh
# 
# Start apache in foreground
# 
# inspiration from: https://github.com/docker-library/httpd/blob/master/2.4/httpd-foreground 
set -e

#Ensure that permanent volumes are correctly set

#/var/www/html, where CQPweb sits
chown -R ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} /var/www/html

# Apache gets grumpy about PID files pre-existing
rm -f ${APACHE_PID_FILE}

exec apache2 -DFOREGROUND
